    spring.application.name=ktx-management
# Cấu hình kết nối CSDL ktx_management cho Nhóm 586
spring.datasource.url=jdbc:mysql://localhost:3306/ktx_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root

spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Context path
server.servlet.context-path=/managektx

# JWT Configuration
jwt.secret=59fbd5522dde4675661e3b3641b4473fd02ae71265e45d0097b02bc6aad29a0a


#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranhannam.ptit.590@gmail.com
spring.mail.password=ehym svwp kdty shea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
